const prisma = require("../../lib/prisma");

const akun = async () => {
  return await prisma.akun.createMany({
    data: [
      {
        id: 3,
        kode: "01",
        nama: "Bank BCA",
        tipe: "DEBET",
        parentId: 1,
      },
      {
        id: 11,
        kode: "01",
        nama: "Hutang Inventory",
        tipe: "KREDIT",
        parentId: 2,
      },
      {
        id: 21,
        kode: "01",
        nama: "Piutang Royality",
        tipe: "DEBET",
        parentId: 16,
      },
      {
        id: 28,
        kode: "01",
        nama: "Daftar Asset",
        tipe: "DEBET",
        parentId: 27,
      },
      {
        id: 31,
        kode: "01",
        nama: "Jual Inventory",
        tipe: "DEBET",
        parentId: 30,
      },
      {
        id: 38,
        kode: "01",
        nama: "Gaji",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 5,
        kode: "02",
        nama: "Bank Jatim",
        tipe: "DEBET",
        parentId: 1,
      },
      {
        id: 12,
        kode: "02",
        nama: "Hutang Royalty",
        tipe: "KREDIT",
        parentId: 2,
      },
      {
        id: 24,
        kode: "02",
        nama: "Piutang Inventory",
        tipe: "DEBET",
        parentId: 16,
      },
      {
        id: 29,
        kode: "02",
        nama: "Penyusutan",
        tipe: "KREDIT",
        parentId: 27,
      },
      {
        id: 32,
        kode: "02",
        nama: "Jual Voucher Non Retail",
        tipe: "DEBET",
        parentId: 30,
      },
      {
        id: 39,
        kode: "02",
        nama: "Pajak",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 13,
        kode: "03",
        nama: "Hutang Kontrak Content",
        tipe: "KREDIT",
        parentId: 2,
      },
      {
        id: 25,
        kode: "03",
        nama: "Piutang Paket Digital (Voucher)",
        tipe: "DEBET",
        parentId: 16,
      },
      {
        id: 33,
        kode: "03",
        nama: "Jual Voucher Retail",
        tipe: "DEBET",
        parentId: 30,
      },
      {
        id: 40,
        kode: "03",
        nama: "BPJS",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 14,
        kode: "04",
        nama: "Hutang Paket Digital (Voucher)",
        tipe: "KREDIT",
        parentId: 2,
      },
      {
        id: 26,
        kode: "04",
        nama: "Piutang Lain-lain",
        tipe: "DEBET",
        parentId: 16,
      },
      {
        id: 34,
        kode: "04",
        nama: "Jual Inventory Non Retail",
        tipe: "DEBET",
        parentId: 30,
      },
      {
        id: 41,
        kode: "04",
        nama: "Administrasi",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 15,
        kode: "05",
        nama: "Hutang Asset",
        tipe: "KREDIT",
        parentId: 2,
      },
      {
        id: 35,
        kode: "05",
        nama: "Iuran Pelanggan",
        tipe: "DEBET",
        parentId: 30,
      },
      {
        id: 42,
        kode: "05",
        nama: "Konsumsi Kantor",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 36,
        kode: "06",
        nama: "Kerjasama Ops",
        tipe: "DEBET",
        parentId: 30,
      },
      {
        id: 45,
        kode: "06",
        nama: "Bayar Hutang",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 44,
        kode: "07",
        nama: "Sumbangan/CSR",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 46,
        kode: "08",
        nama: "Biaya Kontrak Content",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 47,
        kode: "09",
        nama: "Pembelian Inventory",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 1,
        kode: "1",
        nama: "KAS",
        tipe: "DEBET",
        parentId: null,
      },
      {
        id: 48,
        kode: "10",
        nama: "Pembelian Peralatan/Asset",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 49,
        kode: "11",
        nama: "Inventaris Kantor",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 50,
        kode: "12",
        nama: "Biaya Komisi Pemungut",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 51,
        kode: "13",
        nama: "Biaya Bonus Pemungut",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 52,
        kode: "14",
        nama: "Topup K-Vision",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 53,
        kode: "15",
        nama: "Biaya Listrik Bulanan",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 54,
        kode: "16",
        nama: "Biaya Listrik Fastpay",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 55,
        kode: "17",
        nama: "Fee Instalasi Mirah & Kelir",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 56,
        kode: "18",
        nama: "Biaya Peralatan",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 57,
        kode: "19",
        nama: "Ongkos Kirim",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 2,
        kode: "2",
        nama: "HUTANG",
        tipe: "KREDIT",
        parentId: null,
      },
      {
        id: 58,
        kode: "20",
        nama: "Angsuran",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 59,
        kode: "21",
        nama: "Sepeda 2 Unit",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 60,
        kode: "22",
        nama: "BRI Bandi",
        tipe: "KREDIT",
        parentId: 37,
      },
      {
        id: 16,
        kode: "3",
        nama: "PIUTANG",
        tipe: "DEBET",
        parentId: null,
      },
      {
        id: 27,
        kode: "4",
        nama: "ASSEST",
        tipe: "DEBET",
        parentId: null,
      },
      {
        id: 30,
        kode: "5",
        nama: "PENDAPATAN",
        tipe: "DEBET",
        parentId: null,
      },
      {
        id: 37,
        kode: "6",
        nama: "BIAYA-BIAYA",
        tipe: "KREDIT",
        parentId: null,
      },
    ],
    skipDuplicates: true,
  });
};

module.exports = akun;
